// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnwn9dNrHeKDHCWSboJqVpaGn4cr2EVXk',
    appId: '1:312278654272:web:6b58fc27fce243d1b12ea5',
    messagingSenderId: '312278654272',
    projectId: 'taskappfirebase-9e5fe',
    authDomain: 'taskappfirebase-9e5fe.firebaseapp.com',
    storageBucket: 'taskappfirebase-9e5fe.firebasestorage.app',
    measurementId: 'G-XVZ5ZQ36R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkh49y4lgP264Iq6b47LtDp8UGWpZxE8',
    appId: '1:312278654272:android:d1d5234726e9708bb12ea5',
    messagingSenderId: '312278654272',
    projectId: 'taskappfirebase-9e5fe',
    storageBucket: 'taskappfirebase-9e5fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ybFNDlUlxwTcmNpGylfRbk8sO8CSac0',
    appId: '1:312278654272:ios:d823268d30e11b11b12ea5',
    messagingSenderId: '312278654272',
    projectId: 'taskappfirebase-9e5fe',
    storageBucket: 'taskappfirebase-9e5fe.firebasestorage.app',
    iosBundleId: 'com.example.taskAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ybFNDlUlxwTcmNpGylfRbk8sO8CSac0',
    appId: '1:312278654272:ios:d823268d30e11b11b12ea5',
    messagingSenderId: '312278654272',
    projectId: 'taskappfirebase-9e5fe',
    storageBucket: 'taskappfirebase-9e5fe.firebasestorage.app',
    iosBundleId: 'com.example.taskAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnwn9dNrHeKDHCWSboJqVpaGn4cr2EVXk',
    appId: '1:312278654272:web:af2521b353fddb76b12ea5',
    messagingSenderId: '312278654272',
    projectId: 'taskappfirebase-9e5fe',
    authDomain: 'taskappfirebase-9e5fe.firebaseapp.com',
    storageBucket: 'taskappfirebase-9e5fe.firebasestorage.app',
    measurementId: 'G-NRX0J305WL',
  );
}
