// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiLYHuccY64Njs52HsCVKay_dWc13zNMA',
    appId: '1:96201822760:web:df8439dea654bf43a51b1d',
    messagingSenderId: '96201822760',
    projectId: 'fb-auth-bloc-2026',
    authDomain: 'fb-auth-bloc-2026.firebaseapp.com',
    storageBucket: 'fb-auth-bloc-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZoSHsATcx7zWUmrVIFUE9yp3rk7mDwY',
    appId: '1:96201822760:android:599861af76f2cd47a51b1d',
    messagingSenderId: '96201822760',
    projectId: 'fb-auth-bloc-2026',
    storageBucket: 'fb-auth-bloc-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpGAgRNszSxu4IEQHxP7etZl-EK3RgbwI',
    appId: '1:96201822760:ios:1437d5d6d6cb2aeea51b1d',
    messagingSenderId: '96201822760',
    projectId: 'fb-auth-bloc-2026',
    storageBucket: 'fb-auth-bloc-2026.firebasestorage.app',
    iosBundleId: 'com.example.fbAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpGAgRNszSxu4IEQHxP7etZl-EK3RgbwI',
    appId: '1:96201822760:ios:1437d5d6d6cb2aeea51b1d',
    messagingSenderId: '96201822760',
    projectId: 'fb-auth-bloc-2026',
    storageBucket: 'fb-auth-bloc-2026.firebasestorage.app',
    iosBundleId: 'com.example.fbAuthBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiLYHuccY64Njs52HsCVKay_dWc13zNMA',
    appId: '1:96201822760:web:e4f78981fb1564b8a51b1d',
    messagingSenderId: '96201822760',
    projectId: 'fb-auth-bloc-2026',
    authDomain: 'fb-auth-bloc-2026.firebaseapp.com',
    storageBucket: 'fb-auth-bloc-2026.firebasestorage.app',
  );
}
